apiVersion: v1
kind: ConfigMap
metadata:
  name: hey-rodney-config
data:
  rules.yaml: |
    rules:
      - matcher: restart console (pods|parts|pots|ports)
        commands:
          - execute: [ "kubectl", "delete", "pods", "-l", "app=console-backend"]
          - execute: [ "kubectl", "delete", "pods", "-l", "app=console-frontend"]
