apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  # the suffix hash seems just broken
  disableNameSuffixHash: true

secretGenerator:
  - name: watson-sst-credentials
    files:
      - credentials.json

resources:
  - configuration.yaml
  - serviceaccount.yaml
  - role.yaml
  - role-binding.yaml
  - source.yaml
  - service-converter.yaml
  - service-backend.yaml
  - sequence.yaml
