apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hey-rodney-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hey-rodney-backend
subjects:
  - kind: ServiceAccount
    name: hey-rodney-backend
