apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: watson-stt-converter
  labels:
    app.kubernetes.io/part-of: hey-rodney
spec:
  template:
    spec:
      containers:
      - env:
        - name: ONLY_SUBJECTS
          value: voice
        - name: RUST_LOG
          value: debug
        image: ghcr.io/drogue-iot/watson-speech-to-text-converter:latest
        resources:
          limits:
            memory: 32Mi
        volumeMounts:
        - mountPath: /etc/config
          name: credentials
          readOnly: true
      volumes:
      - name: credentials
        secret:
          secretName: watson-sst-credentials
