apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hey-rodney-backend
  labels:
    app.kubernetes.io/name: hey-rodney-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hey-rodney
spec:
  template:
    spec:
      serviceAccountName: hey-rodney-backend
      containers:
        - image: ghcr.io/drogue-iot/hey-rodney-backend:latest
          env:
            - name: QUARKUS_LOG_LEVEL
              value: DEBUG
          resources:
            limits:
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: hey-rodney-config
